// Fixture for TestSourceReportLayoutFlags.al — a report this app compiles, with four Excel
// layouts (each .xlsx generated by alc /generatereportlayout for this dataset; the compiler
// validates an Excel layout's data sheet against the dataset, per data item when
// ExcelLayoutMultipleDataSheets = true) covering the states of the two "Report Layout List" columns under test:
//   SrlPlain     declares neither property          -> not obsolete, sheet configuration Default
//   SrlRetiring  ObsoleteState = Pending            -> obsolete
//   SrlSheets    ExcelLayoutMultipleDataSheets = true  -> Multiple data sheets
//   SrlOneSheet  ExcelLayoutMultipleDataSheets = false -> Single Data sheet
report 67500 "SRL Layout Flags Report"
{
    Caption = 'SRL Layout Flags Report';
    UseRequestPage = false;
    DefaultRenderingLayout = SrlPlain;

    dataset
    {
        dataitem(Numbers; Integer)
        {
            DataItemTableView = where(Number = const(1));
            column(Number; Number) { }
        }
    }

    rendering
    {
        layout(SrlPlain)
        {
            Type = Excel;
            LayoutFile = './SrlPlain.xlsx';
        }
        layout(SrlRetiring)
        {
            Type = Excel;
            LayoutFile = './SrlRetiring.xlsx';
            ObsoleteState = Pending;
            ObsoleteReason = 'Replaced by SrlPlain.';
            ObsoleteTag = '1.0';
        }
        layout(SrlSheets)
        {
            Type = Excel;
            LayoutFile = './SrlSheets.xlsx';
            ExcelLayoutMultipleDataSheets = true;
        }
        layout(SrlOneSheet)
        {
            Type = Excel;
            LayoutFile = './SrlOneSheet.xlsx';
            ExcelLayoutMultipleDataSheets = false;
        }
    }
}
